{
    "idFinancement": "F11222335",
    "objetFinancement": [
        {
            "idObjetFinancement": null,
            "codeObjetFinancement": "02",
            "quotePartObjet": 100.0,
            "codeFamilleObjet": null,
            "gainCEP": null,
            "dateFinTravaux": null,
            "bien": {
                "idBien": null,
                "codeBatiment": "00001",
                "typeBatiment": "Appartement",
                "numeroVoie": null,
                "typeVoie": null,
                "nomRue": null,
                "batiment": null,
                "escalier": null,
                "etage": null,
                "porte": null,
                "codePostal": "75016",
                "nomCommune": null,
                "paysBien": null,
                "adresseComplete": null,
                "codeNormeThermique": null,
                "etatBien": null,
                "typeEnergie": null,
                "codeTypeEnergie": null,
                "codeDepartement": null,
                "codeInseeCommune": null,
                "numeroLot": null,
                "numeroNomRue": null,
                "typeUsage": null,
                "anneeConstruction": 2000,
                "periodeConstruction": null,
                "dateDepotPc": null,
                "dateDebutConstruction": null,
                "surfaceBien": 79.0,
                "bienFinanceLCL": false,
                "numeroFiscalLocal": null,
                "eligibleDpe": null,
                "labelBien": null,
                "coordonneeCartographiqueX": null,
                "coordonneeCartographiqueY": null,
                "prixBien": null,
                "montantFinanceLCL": 10000.0,
                "partLCL": null,
                "dpeActuel": {
                    "idDpe": null,
                    "numeroDpe": "2337E1287825F",
                    "codeModeleDpeType": null,
                    "estimationCep": 100.0,
                    "classeCep": "A",
                    "estimationGes": 60.0,
                    "classeGes": "B",
                    "dateEtablissementDpe": null,
                    "dateReceptionDpe": null,
                    "dateFinValiditeDpe": null,
                    "sirenDiagnostiqueur": null,
                    "modelDpe": null,
                    "numeroDpeRemplace": null,
                    "versionDpe": null,
                    "methodeDpeApplique": null
                }
            },
            "dpeAvantTravaux": null,
            "dpeApresTravaux": null,
            "alignement": null,
            "eligibilite": null,
            "garantie": null,
            "piecesJustificatives": null,
            "statut": 0
        }
    ],
    "alignement": null,
    "eligibilite": null,
    "intervenant": {
        "idIntervenant": null,
        "idReper": [
            "8415595180"
        ]
    },
    "indicateurFinancementDedie": null,
    "indicateurNatureDurable": null,
    "typeRisqueClimatiqueAttenue": null,
    "codeApplicatifOrigine": null,
    "indicateurReprise": false,
    "statut": 0,
    "agenceCompte": null,
    "valeurTravaux": null
}
